In [16]:
import pandas as pd
import numpy as np             

matches = pd.read_csv('Dataset/matches.csv')
deliveries = pd.read_csv('Dataset/deliveries.csv')

In [17]:
matches.head(10)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,N,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde
9,1304111,Mumbai,2022-05-17,2022,65,Sunrisers Hyderabad,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Sunrisers Hyderabad,Runs,3.0,NaN,RA Tripathi,"['Abhishek Sharma', 'PK Garg', 'RA Tripathi', ...","['RG Sharma', 'Ishan Kishan', 'DR Sams', 'Tila...",CB Gaffaney,N Pandit

In [18]:
deliveries.head(10)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
5,1312200,1,0,6,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
6,1312200,1,1,1,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
7,1312200,1,1,2,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
8,1312200,1,1,3,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,4,0,4,0,0,NaN,NaN,NaN,Rajasthan Royals
9,1312200,1,1,4,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [19]:
''' Q1. Load the IPL dataset. Create a Series of total runs per batsman with player names as the index.
Examine run distribution using descriptive statistics and identify the top 10 run-scorers.'''

' Q1. Load the IPL dataset. Create a Series of total runs per batsman with player names as the index.\nExamine run distribution using descriptive statistics and identify the top 10 run-scorers.'

In [20]:
totalRuns = pd.Series(deliveries.groupby('batter')['total_run'].sum())
display(totalRuns.head())

batter
A Ashish Reddy    288
A Badoni          173
A Chandila          4
A Chopra           58
A Choudhary        25
Name: total_run, dtype: int64

In [21]:
desc = deliveries['batsman_run'].describe()
desc

count    225954.000000
mean          1.243523
std           1.618166
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           6.000000
Name: batsman_run, dtype: float64

In [22]:
top10 = totalRuns.sort_values(ascending=False)
top10.head(10)

batter
V Kohli           6876
S Dhawan          6561
DA Warner         6191
RG Sharma         6083
SK Raina          5780
AB de Villiers    5354
CH Gayle          5336
RV Uthappa        5246
MS Dhoni          5221
KD Karthik        4572
Name: total_run, dtype: int64

In [23]:
"""Q2. Compute the strike rate (runs / balls faced × 100) of top batsmen using ufuncs.
Compare performance in the powerplay (overs 1–6) versus death overs (overs 17–20)."""

'Q2. Compute the strike rate (runs / balls faced × 100) of top batsmen using ufuncs.\nCompare performance in the powerplay (overs 1–6) versus death overs (overs 17–20).'

In [24]:
runs = pd.Series(deliveries.groupby('batter')['total_run'].sum())
balls = pd.Series(deliveries.groupby('batter')['ballnumber'].count())

In [25]:
strikeRate = (runs / balls) * 100

In [26]:
topBatsmen = runs[runs > 5000].index
topBatsmen

Index(['AB de Villiers', 'CH Gayle', 'DA Warner', 'MS Dhoni', 'RG Sharma',
       'RV Uthappa', 'S Dhawan', 'SK Raina', 'V Kohli'],
      dtype='object', name='batter')

In [27]:
sr_top = strikeRate.loc[topBatsmen].sort_values(ascending=False)

sr_top

batter
AB de Villiers    153.541726
CH Gayle          151.763367
DA Warner         143.542778
SK Raina          138.376825
MS Dhoni          137.322462
RV Uthappa        133.587981
RG Sharma         131.325561
V Kohli           130.573490
S Dhawan          129.077317
dtype: float64

In [28]:
powerplay = deliveries[deliveries['overs'] <= 6]
deathovers = deliveries[deliveries['overs'] > 6]

In [29]:
pp_runs = powerplay.groupby('batter')['total_run'].sum()
pp_balls = powerplay.groupby('batter')['ballnumber'].size()

pp_sr = pp_runs / pp_balls * 100

In [30]:
do_runs = deathovers.groupby('batter')['total_run'].sum()
do_balls = deathovers.groupby('batter')['ballnumber'].size()

do_sr = do_runs / do_balls * 100

In [31]:
comparision = pd.DataFrame({
    'Power Play' : pp_sr,
    'Death over' : do_sr
}).loc[topBatsmen].sort_values(by='Death over', ascending=False)
comparision

                Power Play  Death over
batter
CH Gayle        138.208232  171.054445
AB de Villiers  120.121951  163.817023
DA Warner       138.085540  150.753498
SK Raina        130.753968  142.701689
RV Uthappa      125.832492  141.491003
V Kohli         115.471869  141.443501
MS Dhoni         82.000000  139.594743
RG Sharma       117.110716  139.483520
S Dhawan        124.110141  136.104513

In [32]:
"""Q3. Apply hierarchical indexing on 'batting_team' and 'over'. 
Examine average runs per over at each hierarchical level using xs() and groupby.
Identify team scoring patterns."""

"Q3. Apply hierarchical indexing on 'batting_team' and 'over'. \nExamine average runs per over at each hierarchical level using xs() and groupby.\nIdentify team scoring patterns."

In [33]:
hierarchy = deliveries.set_index(['BattingTeam', 'overs'])

In [34]:
runs_per_over = hierarchy.groupby(level=['BattingTeam', 'overs'])['total_run'].mean()
runs_per_over.head()

BattingTeam          overs
Chennai Super Kings  0        0.837817
                     1        1.035195
                     2        1.229280
                     3        1.342636
                     4        1.392662
Name: total_run, dtype: float64

In [35]:
runs_per_over.xs('Chennai Super Kings').head()

overs
0    0.837817
1    1.035195
2    1.229280
3    1.342636
4    1.392662
Name: total_run, dtype: float64

In [36]:
hierarchy.head()

                             ID  innings  ballnumber       batter  \
BattingTeam      overs
Rajasthan Royals 0      1312200        1           1  YBK Jaiswal
                 0      1312200        1           2  YBK Jaiswal
                 0      1312200        1           3   JC Buttler
                 0      1312200        1           4  YBK Jaiswal
                 0      1312200        1           5  YBK Jaiswal

                                bowler  non-striker extra_type  batsman_run  \
BattingTeam      overs
Rajasthan Royals 0      Mohammed Shami   JC Buttler        NaN            0
                 0      Mohammed Shami   JC Buttler    legbyes            0
                 0      Mohammed Shami  YBK Jaiswal        NaN            1
                 0      Mohammed Shami   JC Buttler        NaN            0
                 0      Mohammed Shami   JC Buttler        NaN            0

                        extras_run  total_run  non_boundary  isWicketDelivery  \
BattingTeam      overs
Rajasthan Royals 0               0          0             0                 0
                 0               1          1             0                 0
                 0               0          1             0                 0
                 0               0          0             0                 0
                 0               0          0             0                 0

                       player_out kind fielders_involved
BattingTeam      overs
Rajasthan Royals 0            NaN  NaN               NaN
                 0            NaN  NaN               NaN
                 0            NaN  NaN               NaN
                 0            NaN  NaN               NaN
                 0            NaN  NaN               NaN

In [37]:
over3 = runs_per_over.xs(2, level='overs')
over3.head()

BattingTeam
Chennai Super Kings    1.229280
Deccan Chargers        1.217204
Delhi Capitals         1.451031
Delhi Daredevils       1.252747
Gujarat Lions          1.606557
Name: total_run, dtype: float64

In [38]:
"""Q4. Create a 'Player Impact Score' combining runs, fours, sixes, and wickets using normalized ufunc weights.
Rank all players and construct an impact leaderboard."""

"Q4. Create a 'Player Impact Score' combining runs, fours, sixes, and wickets using normalized ufunc weights.\nRank all players and construct an impact leaderboard."

In [39]:
deliveries.fillna(0)
runs = deliveries.groupby('batter')['batsman_run'].sum()
fours = deliveries[deliveries['batsman_run'] == 4].groupby(['batter']).size()
sixes = deliveries[deliveries['batsman_run'] == 6].groupby(['batter']).size()
wickets = deliveries[deliveries['isWicketDelivery'] == 1].groupby(['batter']).size()

In [40]:
impact = pd.concat([runs, fours, sixes, wickets], axis=1).fillna(0)
impact.columns=['runs', 'fours',  'sixes', 'wickets']
impact

                runs  fours  sixes  wickets
batter
A Ashish Reddy   280   16.0   15.0     15.0
A Badoni         161   11.0    7.0      9.0
A Chandila         4    0.0    0.0      1.0
A Chopra          53    7.0    0.0      5.0
A Choudhary       25    1.0    1.0      2.0
...              ...    ...    ...      ...
Yash Dayal         0    0.0    0.0      1.0
Yashpal Singh     47    5.0    0.0      4.0
Younis Khan        3    0.0    0.0      1.0
Yuvraj Singh    2754  218.0  149.0    109.0
Z Khan           117   11.0    2.0     15.0

[605 rows x 4 columns]

In [41]:
import numpy as np
norm = impact / impact.max()
impact['impact_score'] = np.add.reduce([
    norm['runs'] * 0.4,
    norm['fours'] * 0.2,
    norm['sixes'] * 0.2,
    norm['wickets'] * 0.2
])
impact.sort_values(by='impact_score', ascending=False)
impact.head()

                runs  fours  sixes  wickets  impact_score
batter
A Ashish Reddy   280   16.0   15.0     15.0      0.044583
A Badoni         161   11.0    7.0      9.0      0.025613
A Chandila         4    0.0    0.0      1.0      0.001226
A Chopra          53    7.0    0.0      5.0      0.010119
A Choudhary       25    1.0    1.0      2.0      0.004320

In [42]:
"""Q5. Examine missing values in dismissal-related columns. 
Determine the effect of replacing NaN with 'not out' versus dropping those rows on overall bowling statistics."""

"Q5. Examine missing values in dismissal-related columns. \nDetermine the effect of replacing NaN with 'not out' versus dropping those rows on overall bowling statistics."

In [43]:
deliveries[['player_out', 'kind']].isnull().sum()

player_out    214803
kind          214803
dtype: int64

In [44]:
deliveries[['player_out', 'kind']] = deliveries[['player_out', 'kind']].fillna('not out')
deliveries[['player_out', 'kind']].isnull().sum()

player_out    0
kind          0
dtype: int64

In [45]:
df_replace = deliveries
wickets_replace = df_replace.groupby('bowler')['isWicketDelivery'].sum()
total_wickets_replace = wickets_replace.sum()

df_drop = df_replace.dropna(subset=['player_out', 'kind'])

wickets_drop = df_drop.groupby('bowler')['isWicketDelivery'].sum()
total_wickets_drop = wickets_drop.sum()

print("Total wickets (NaN replaced):", total_wickets_replace)
print("Total wickets (NaN dropped):", total_wickets_drop)

Total wickets (NaN replaced): 11151
Total wickets (NaN dropped): 11151

In [46]:
"""Q6. Using boolean indexing, filter deliveries where extras are greater than zero. 
Examine which teams concede the most extras and in which match phases they occur."""

'Q6. Using boolean indexing, filter deliveries where extras are greater than zero. \nExamine which teams concede the most extras and in which match phases they occur.'

In [47]:
df = deliveries.merge(matches, left_on='ID', right_on='ID')

df['bowling_team'] = df.apply(
    lambda col: col['Team1'] if col['BattingTeam'] == col['Team2'] else col['Team2'], axis=1
)

extras = df[df['extras_run'] > 0]


extras['phase'] = extras['overs'].apply(
    lambda x: 'Powerplay' if x<=6 else ('Middle' if x<=15 else 'Death')
)

extras[['BattingTeam', 'extras_run']]

C:\Users\sanja\AppData\Local\Temp\ipykernel_8740\1454108575.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extras['phase'] = extras['overs'].apply(

                        BattingTeam  extras_run
1                  Rajasthan Royals           1
65                 Rajasthan Royals           1
138                  Gujarat Titans           5
148                  Gujarat Titans           1
151                  Gujarat Titans           1
...                             ...         ...
225917  Royal Challengers Bangalore           1
225933  Royal Challengers Bangalore           2
225945  Royal Challengers Bangalore           1
225949  Royal Challengers Bangalore           1
225952  Royal Challengers Bangalore           1

[12049 rows x 2 columns]

In [48]:
mostExtras = extras.groupby('bowling_team')['extras_run'].sum().sort_values(ascending=False)
mostExtras

bowling_team
Mumbai Indians                 1970
Royal Challengers Bangalore    1899
Kolkata Knight Riders          1704
Rajasthan Royals               1689
Kings XI Punjab                1571
Chennai Super Kings            1554
Delhi Daredevils               1268
Sunrisers Hyderabad            1004
Deccan Chargers                 659
Delhi Capitals                  451
Pune Warriors                   335
Punjab Kings                    245
Gujarat Lions                   188
Lucknow Super Giants            138
Gujarat Titans                  114
Rising Pune Supergiant          111
Kochi Tuskers Kerala            110
Rising Pune Supergiants         108
Name: extras_run, dtype: int64

In [49]:
extras.groupby('phase')['extras_run'].sum()

phase
Death        3421
Middle       5725
Powerplay    5972
Name: extras_run, dtype: int64

In [50]:
"""Q7. Design a match-phase classifier using apply() that labels each delivery as 'Powerplay', 'Middle', or 'Death' overs. 
Build a team-wise phase performance matrix using pivot_table."""

"Q7. Design a match-phase classifier using apply() that labels each delivery as 'Powerplay', 'Middle', or 'Death' overs. \nBuild a team-wise phase performance matrix using pivot_table."

In [51]:
import pandas as pd

deliveries['phase'] = deliveries['overs'].apply(
    lambda x: 'Powerplay' if x<=6 else ('Middle' if x<=15 else 'Death')
)

result_matrix = pd.pivot_table(
    deliveries,
    values='total_run',
    index='BattingTeam',
    columns='phase',
    aggfunc='mean'
)

result_matrix

phase                           Death    Middle  Powerplay
BattingTeam
Chennai Super Kings          1.698899  1.284041   1.196289
Deccan Chargers              1.530440  1.228948   1.186394
Delhi Capitals               1.598090  1.272154   1.290252
Delhi Daredevils             1.600952  1.246232   1.212981
Gujarat Lions                1.502447  1.297677   1.380410
Gujarat Titans               1.687500  1.309336   1.219198
Kings XI Punjab              1.536014  1.316291   1.239764
Kochi Tuskers Kerala         1.415966  1.101108   1.236334
Kolkata Knight Riders        1.584227  1.278520   1.211353
Lucknow Super Giants         1.747283  1.395884   1.164087
Mumbai Indians               1.674080  1.279752   1.185978
Pune Warriors                1.350546  1.152946   1.093463
Punjab Kings                 1.493399  1.301089   1.275184
Rajasthan Royals             1.537755  1.288594   1.207413
Rising Pune Supergiant       1.594828  1.214035   1.258250
Rising Pune Supergiants      1.730469  1.225175   1.221675
Royal Challengers Bangalore  1.703528  1.303774   1.178000
Sunrisers Hyderabad          1.535650  1.256659   1.234531

In [52]:
"""Q8. Examine how index alignment behaves when merging a bowler-wise wickets Series with a bowler- wise runs-conceded Series. 
Compute economy rate using aligned index arithmetic."""

'Q8. Examine how index alignment behaves when merging a bowler-wise wickets Series with a bowler- wise runs-conceded Series. \nCompute economy rate using aligned index arithmetic.'

In [53]:
import pandas as pd

wickets = deliveries.groupby('bowler')['isWicketDelivery'].sum()

runs = deliveries.groupby('bowler')['total_run'].sum()

balls = deliveries.groupby('bowler').size()

economy = (runs / balls) * 6

result = pd.concat([wickets, runs, balls, economy], axis=1)
result.columns = ['wickets', 'concededRuns', 'balls', 'economy']

result.head()

                wickets  concededRuns  balls    economy
bowler
A Ashish Reddy       19           400    270   8.888889
A Badoni              2            12     12   6.000000
A Chandila           11           245    234   6.282051
A Choudhary           5           144    108   8.000000
A Dananjaya           0            47     25  11.280000

In [54]:
"""Q9. Using hierarchical indexing on season and team, examine total runs, wickets, and extras per season per team. 
Use unstack() to build a season comparison matrix."""

'Q9. Using hierarchical indexing on season and team, examine total runs, wickets, and extras per season per team. \nUse unstack() to build a season comparison matrix.'

In [55]:
import pandas as pd

df = deliveries.merge(matches[['ID','Season']], on='ID')

stats = df.groupby(['Season','BattingTeam']).agg({
    'total_run': 'sum',
    'isWicketDelivery': 'sum',
    'extras_run': 'sum'
})

matrix = stats.unstack(level=0)

matrix

                            total_run                                          \
Season                        2007/08    2009 2009/10    2011    2012    2013
BattingTeam
Chennai Super Kings            2520.0  2231.0  2604.0  2560.0  2831.0  2778.0
Deccan Chargers                2229.0  2408.0  2374.0  2140.0  2312.0     NaN
Delhi Capitals                    NaN     NaN     NaN     NaN     NaN     NaN
Delhi Daredevils               2118.0  2131.0  2155.0  2087.0  2645.0  2245.0
Gujarat Lions                     NaN     NaN     NaN     NaN     NaN     NaN
Gujarat Titans                    NaN     NaN     NaN     NaN     NaN     NaN
Kings XI Punjab                2464.0  1928.0  2288.0  2224.0  2390.0  2428.0
Kochi Tuskers Kerala              NaN     NaN     NaN  1901.0     NaN     NaN
Kolkata Knight Riders          1942.0  1772.0  2144.0  2023.0  2504.0  2290.0
Lucknow Super Giants              NaN     NaN     NaN     NaN     NaN     NaN
Mumbai Indians                 2080.0  1897.0  2738.0  2288.0  2462.0  2975.0
Pune Warriors                     NaN     NaN     NaN  1775.0  2321.0  2262.0
Punjab Kings                      NaN     NaN     NaN     NaN     NaN     NaN
Rajasthan Royals               2601.0  1706.0  2179.0  1687.0  2516.0  2705.0
Rising Pune Supergiant            NaN     NaN     NaN     NaN     NaN     NaN
Rising Pune Supergiants           NaN     NaN     NaN     NaN     NaN     NaN
Royal Challengers Bangalore    1983.0  2280.0  2401.0  2469.0  2472.0  2601.0
Sunrisers Hyderabad               NaN     NaN     NaN     NaN     NaN  2318.0

                                                             ... extras_run  \
Season                         2014    2015    2016    2017  ...       2013
BattingTeam                                                  ...
Chennai Super Kings          2650.0  2725.0     NaN     NaN  ...      107.0
Deccan Chargers                 NaN     NaN     NaN     NaN  ...        NaN
Delhi Capitals                  NaN     NaN     NaN     NaN  ...        NaN
Delhi Daredevils             2081.0  2168.0  2104.0  2219.0  ...      131.0
Gujarat Lions                   NaN     NaN  2450.0  2412.0  ...        NaN
Gujarat Titans                  NaN     NaN     NaN     NaN  ...        NaN
Kings XI Punjab              2987.0  2018.0  2134.0  2207.0  ...      116.0
Kochi Tuskers Kerala            NaN     NaN     NaN     NaN  ...        NaN
Kolkata Knight Riders        2499.0  2044.0  2263.0  2484.0  ...      156.0
Lucknow Super Giants            NaN     NaN     NaN     NaN  ...        NaN
Mumbai Indians               2353.0  2734.0  2194.0  2800.0  ...      130.0
Pune Warriors                   NaN     NaN     NaN     NaN  ...       79.0
Punjab Kings                    NaN     NaN     NaN     NaN  ...        NaN
Rajasthan Royals             2166.0  2143.0     NaN     NaN  ...      134.0
Rising Pune Supergiant          NaN     NaN     NaN  2470.0  ...        NaN
Rising Pune Supergiants         NaN     NaN  2063.0     NaN  ...        NaN
Royal Challengers Bangalore  2093.0  2311.0  2981.0  1845.0  ...      141.0
Sunrisers Hyderabad          2102.0  2210.0  2673.0  2349.0  ...      121.0

                                                                               \
Season                        2014   2015   2016   2017   2018   2019 2020/21
BattingTeam
Chennai Super Kings          131.0  161.0    NaN    NaN  111.0  127.0    96.0
Deccan Chargers                NaN    NaN    NaN    NaN    NaN    NaN     NaN
Delhi Capitals                 NaN    NaN    NaN    NaN    NaN  101.0   122.0
Delhi Daredevils             103.0  107.0  109.0   88.0   93.0    NaN     NaN
Gujarat Lions                  NaN    NaN  132.0  101.0    NaN    NaN     NaN
Gujarat Titans                 NaN    NaN    NaN    NaN    NaN    NaN     NaN
Kings XI Punjab              163.0  116.0   83.0  108.0   86.0  103.0    93.0
Kochi Tuskers Kerala           NaN    NaN    NaN    NaN    NaN    NaN     NaN
Kolkata Knight Riders        117.0  105.0  130.0  130.0  104.0  114.0    98.0
Lucknow Super Giants           NaN    NaN    NaN    NaN    NaN    NaN     NaN
Mumbai Indians               118.0  123.0  103.0  167.0  125.0  107.0    96.0
Pune Warriors                  NaN    NaN    NaN    NaN    NaN    NaN     NaN
Punjab Kings                   NaN    NaN    NaN    NaN    NaN    NaN     NaN
Rajasthan Royals              96.0  100.0    NaN    NaN   81.0   91.0    91.0
Rising Pune Supergiant         NaN    NaN    NaN  100.0    NaN    NaN     NaN
Rising Pune Supergiants        NaN    NaN  101.0    NaN    NaN    NaN     NaN
Royal Challengers Bangalore  101.0  121.0  118.0   85.0   82.0   79.0   120.0
Sunrisers Hyderabad          159.0   93.0  124.0   87.0  121.0  105.0   134.0


Season                        2021   2022
BattingTeam
Chennai Super Kings          126.0  123.0
Deccan Chargers                NaN    NaN
Delhi Capitals               108.0  123.0
Delhi Daredevils               NaN    NaN
Gujarat Lions                  NaN    NaN
Gujarat Titans                 NaN  146.0
Kings XI Punjab                NaN    NaN
Kochi Tuskers Kerala           NaN    NaN
Kolkata Knight Riders        136.0  114.0
Lucknow Super Giants           NaN  143.0
Mumbai Indians               101.0  117.0
Pune Warriors                  NaN    NaN
Punjab Kings                  89.0  150.0
Rajasthan Royals             109.0  136.0
Rising Pune Supergiant         NaN    NaN
Rising Pune Supergiants        NaN    NaN
Royal Challengers Bangalore  122.0  178.0
Sunrisers Hyderabad          119.0  113.0

[18 rows x 45 columns]

In [56]:
"""Q10. Build a comprehensive IPL analytics report covering null handling, hierarchical batting and bowling analysis, ufunc performance metrics, and phase-wise comparisons."""

'Q10. Build a comprehensive IPL analytics report covering null handling, hierarchical batting and bowling analysis, ufunc performance metrics, and phase-wise comparisons.'

In [57]:
import pandas as pd
import numpy as np

df = deliveries.merge(matches[['ID','Season']], on='ID')

df['player_out'] = df['player_out'].fillna('NOT out')
df['kind'] = df['kind'].fillna('Not out')
df.isnull().sum().head()

ID            0
innings       0
overs         0
ballnumber    0
batter        0
dtype: int64

In [58]:
batting = df.groupby(['Season','BattingTeam'])['total_run'].sum()

bowling = df.groupby(['Season','bowler'])['isWicketDelivery'].sum()

In [59]:
runs = df.groupby('batter')['batsman_run'].sum()
balls = df.groupby('batter').size()
strike_rate = np.divide(runs, balls) * 100

In [ ]:
df['phase'] = df['overs'].apply(lambda x: 'PP' if x<=6 else ('Middle' if x<=15 else 'Death'))
matrix = pd.pivot_table(
    df,
    values='total_run',
    index='BattingTeam',
    columns='phase',
    aggfunc='mean'
)

In [61]:
batting.head()

Season   BattingTeam
2007/08  Chennai Super Kings      2520
         Deccan Chargers          2229
         Delhi Daredevils         2118
         Kings XI Punjab          2464
         Kolkata Knight Riders    1942
Name: total_run, dtype: int64

In [62]:
bowling.head()

Season   bowler
2007/08  A Kumble      8
         A Mishra     11
         A Nehra      14
         A Nel         1
         A Symonds     0
Name: isWicketDelivery, dtype: int64

In [63]:
strike_rate.head()

batter
A Ashish Reddy    142.857143
A Badoni          115.827338
A Chandila         57.142857
A Chopra           70.666667
A Choudhary       125.000000
dtype: float64

In [67]:
matrix.head()

                    total_run                                                  \
Season                2007/08    2009 2009/10    2011    2012    2013    2014
BattingTeam
Chennai Super Kings    2520.0  2231.0  2604.0  2560.0  2831.0  2778.0  2650.0
Deccan Chargers        2229.0  2408.0  2374.0  2140.0  2312.0     NaN     NaN
Delhi Capitals            NaN     NaN     NaN     NaN     NaN     NaN     NaN
Delhi Daredevils       2118.0  2131.0  2155.0  2087.0  2645.0  2245.0  2081.0
Gujarat Lions             NaN     NaN     NaN     NaN     NaN     NaN     NaN

                                             ... extras_run                \
Season                 2015    2016    2017  ...       2013   2014   2015
BattingTeam                                  ...
Chennai Super Kings  2725.0     NaN     NaN  ...      107.0  131.0  161.0
Deccan Chargers         NaN     NaN     NaN  ...        NaN    NaN    NaN
Delhi Capitals          NaN     NaN     NaN  ...        NaN    NaN    NaN
Delhi Daredevils     2168.0  2104.0  2219.0  ...      131.0  103.0  107.0
Gujarat Lions           NaN  2450.0  2412.0  ...        NaN    NaN    NaN


Season                2016   2017   2018   2019 2020/21   2021   2022
BattingTeam
Chennai Super Kings    NaN    NaN  111.0  127.0    96.0  126.0  123.0
Deccan Chargers        NaN    NaN    NaN    NaN     NaN    NaN    NaN
Delhi Capitals         NaN    NaN    NaN  101.0   122.0  108.0  123.0
Delhi Daredevils     109.0   88.0   93.0    NaN     NaN    NaN    NaN
Gujarat Lions        132.0  101.0    NaN    NaN     NaN    NaN    NaN

[5 rows x 45 columns]